### ISSUE TITLE
how to import the adblock list from a file

### ISSUE THREAD

**Issue by youerning** [seedifferently/nogo#3]
In fact, the nogo is not tend to be worked well in china or other region。
my be the service import the adblock list from  adblock plus of chrome extension is well or compatible with the adblock list。
I try to do this as below，the affect is not good。
./nogo --dns-proxyto "xxx.x.xx.x:53" --import easylist.txt
head easylist.txt -n 20
==> easylist.txt <==
[Adblock Plus 2.0]
! Version: 201702261840
! Title: EasyList
! Last modified: 26 Feb 2017 18:40 UTC
! Expires: 4 days (update frequency)
! Homepage: https://easylist.to/
! Licence: https://easylist.to/pages/licence.html
!
! Please report any unblocked adverts or problems
! in the forums (https://forums.lanik.us/)
&ad.vid=
&ad_box_
&ad_channel=
&ad_classid=

**Comment by seedifferently** [comment]
Hello,

As the `-import` switch's help output says, the import file must be in the format of a "traditional" hosts file (or one domain per line). 

Browser plugins like adblock plus use a completely different type of file format since they are meant for the browser and therefore target sources to block in a much different way.

Check out one of these lists instead for the appropriate format: https://github.com/StevenBlack/hosts
